apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: "content.halo.run"
    kind: Category
  formSchema:
    - $formkit: "select"
      name: "color"
      id: "color"
      key: "color"
      label: "背景颜色"
      help: "自定义分类背景颜色"
      placeholder: 请选择颜色
      clearable: true
      options:
        - label: 静谧星空
          value: gradient-bg-1
        - label: 玫红暮光
          value: gradient-bg-2
        - label: 蓝海微风
          value: gradient-bg-3
        - label: 翠绿清泉
          value: gradient-bg-4
        - label: 花漾晨曦
          value: gradient-bg-5
        - label: 梦境薄雾
          value: gradient-bg-6
        - label: 樱花晨曦
          value: gradient-bg-7
        - label: 梦幻紫霞
          value: gradient-bg-8
        - label: 奶油草莓
          value: gradient-bg-9
        - label: 薄荷清泉
          value: gradient-bg-10
        - label: 暖橙日落
          value: gradient-bg-11
        - label: 烈焰余晖
          value: gradient-bg-12
        - label: 深海极光
          value: gradient-bg-13
        - label: 云雾轻纱
          value: gradient-bg-14
        - label: 蜜桃气泡
          value: gradient-bg-15
    - $formkit: "text"
      name: "font"
      id: "font"
      key: "font"
      label: "分类图标"
      clearable: true
      help: "字体链接:https://fontawesome.com/search?f=classic&s=solid&ic=free&o=r"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "text"
      name: "MenuFont"
      id: "MenuFont"
      key: "MenuFont"
      label: "图标SVG"
      clearable: true
      help: "建议设置width和height为20"

---

apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: post-share-pan
spec:
  targetRef:
    group: "content.halo.run"
    kind: Post
  formSchema:
    - help: 输入为空时，前台不渲染
    - $formkit: text
      name: shareBaidu
      key: shareBaidu
      id: shareBaidu
      label: 百度网盘
      placeholder: 请输入百度网盘链接
      clearable: true
    - $formkit: text
      name: baiduPwd
      key: baiduPwd
      id: baiduPwd
      label: 百度网盘提取码
      if: "$get('shareBaidu').value"
    - $formkit: text
      name: share123
      key: share123
      id: share123
      label: 123云盘
      placeholder: 请输入123云盘链接
      clearable: true
    - $formkit: text
      name: pwd123
      key: pwd123
      id: pwd123
      label: 123云盘提取码
      if: "$get('share123').value"
    - $formkit: text
      name: shareKua
      key: shareKua
      id: shareKua
      label: 夸克网盘链接
      placeholder: 请输入夸克网盘链接
      clearable: true
    - $formkit: text
      name: kuaPwd
      key: kuaPwd
      id: kuaPwd
      label: 夸克网盘提取码
      if: "$get('shareKua').value"
    - $formkit: text
      name: shareOther
      key: shareOther
      id: shareOther
      label: 其他网盘链接
      placeholder: 请输入其他网盘链接
      clearable: true
    - $formkit: text
      name: otherName
      key: otherName
      id: otherName
      label: 其他网盘名称
      placeholder: 请输入其他网盘名称
      clearable: true
      if: "$get('shareOther').value"
    - $formkit: text
      name: otherPwd
      key: otherPwd
      id: otherPwd
      label: 其他网盘提取码
      clearable: true
      if: "$get('shareOther').value"
